version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: mysecretpassword
            PGDATA: /var/lib/postgresql/data/pgdata
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 10s
            retries: 5
    redis:
        image: redis
    app:
        build: .
        command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        depends_on:
            - db:
                condition: service_healthy
            - redis
        volumes:
            - .:/code
    celery_worker:
        build: .
        command: celery -A config worker -l info
        depends_on:
            - db:
                condition: service_healthy
            - redis
        volumes:
            - .:/code
    celery_beat:
        build: .
        command: celery -A config beat -l info
        depends_on:
            - db:
                condition: service_healthy
            - redis
        volumes:
            - .:/code